config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cafes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafe.rb
class Cafe < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  def new
    @cafe = Cafe.new
  end

  def create
    @cafe = Cafe.new(cafe_attributes)

    if @cafe.save
      redirect_to cafes_path
    else
      flash[:error] = 'Something terrible has happened.'
      render :new
    end
  end

  def index
    @cafes = Cafe.all
  end

  def show
    @cafe = Cafe.find params[:id]
  end

  private

  def cafe_attributes
    params.require(:cafe).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/views/cafes/index.html.erb
<h1>Hello, here is a wonderful list of Cafés</h1>
<ul>
  <% @cafes.each do |cafe| %>
    <li>
      <h2><%= link_to cafe.name, cafe_path(cafe) %></h2>
      <p><%= cafe.description %></p>
    </li>
  <% end %>
</ul>

app/views/cafes/new.html.erb
<h1>Chris <em>is</em> the best</h1>

<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% end %>

<%= form_for @cafe, url: {action: "create"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit 'GO!!!' %>
<% end %>

app/views/cafes/show.html.erb
<h2><%= @cafe.name %></h2>
<p><%= @cafe.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeSociety</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to 'Home', cafes_path %>
      <%= link_to 'New', new_cafe_path %>
    </header>
    <%= yield %>
  </body>
</html>